# Generated by Django 5.0.1 on 2024-02-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('trade_code', models.CharField(max_length=200)),
                ('high', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('open', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('close', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
